### PR TITLE
Allow underscores in workplace name

### PR DESCRIPTION
**Pull request by robsyme**
The existing pattern assumes that all org and workspace identifiers are `a-z` (no capital letters, underscores, numbers or dashes).

This PR adjusts the pattern to fix the pattern to match the one used by Seqera Platform - identifiers must begin and end with `[a-zA-Z0-9]` but can otherwise contain (up to 38 chars of) letters lowercase, letters uppercase, numbers, dashes or underscores (`[a-zA-Z0-9]|[-_]`).

### CODE REVIEW

**Review by laramiellindsey — APPROVED** [review]

**Comment by maxulysse** [comment]
Can you update the snapshots?

**Comment by robsyme** [comment]
@maxulysse Snapshots updated. The remaining failures seem to be specific to the CI runner - I get passes when testing on Gitpod.

**Comment by maxulysse** [comment]
OK, I'd say that the failing tests seems to be connected to Nextflow version, since the one that fails are `nf-latest-everything`.
I'd rather we don't merge it until we know for sure what is the cause, and even try to fix.

**Comment by robsyme** [comment]
Tests look good. I'll update the changelog and then merge.

**Pull request merged**
